server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.161:10086/eureka/
    eureka.client.registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    item-service: /item/**
  host:
    connect-timeout-millis: 20000
    connection-request-timeout-millis: 60000






